name: MAUI CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8.0.414
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.414

      - name: Install MAUI workload
        run: dotnet workload install maui --ignore-failed-sources

      # ✅ Restore with RID so assets.json includes win10-x64
      - name: Restore dependencies
        run: dotnet restore Grocery.App/Grocery.App.csproj -p:TargetFramework=net8.0-windows10.0.19041.0 -p:RuntimeIdentifier=win10-x64
      # Optional build (publish already builds, but this keeps CI flow familiar)
      - name: Build MAUI app (Windows)
        run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-windows10.0.19041.0 -r win10-x64 --no-restore -p:PublishReadyToRun=false

      # ✅ Publish into artifacts
      - name: Package MAUI app
        run: dotnet publish Grocery.App/Grocery.App.csproj -c Release -f net8.0-windows10.0.19041.0 -r win10-x64 -o ./artifacts/maui -p:WindowsPackageType=None -p:PublishSingleFile=false -p:PublishReadyToRun=false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GroceryApp
          path: artifacts/maui
