name: MAUI (Windows TFM) Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ensure global.json (SDK 8.0.414)
        shell: pwsh
        run: |
          $json = @{ sdk = @{ version = "8.0.414"; rollForward = "disable" } } | ConvertTo-Json -Compress
          Set-Content -Path global.json -Value $json -Encoding UTF8

      - name: Setup .NET (from global.json)
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore (Windows TFM only)
        run: dotnet restore Grocery.App/Grocery.App.csproj -f net8.0-windows10.0.19041.0 -r win-x64

      - name: Build (Windows TFM only)
        run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-windows10.0.19041.0 -r win-x64 -p:PublishReadyToRun=false --no-restore
